### ISSUE TITLE
longitude and latitude sorting.

### ISSUE THREAD

**Issue by designerfuzzi** [iceweasel1/COVID-19-Germany#1]
in german.csv
longitude and latitude are exchanged.
maybe just re-sorting the header row as a fix.

here an example :)
city = Latitude, Longitude
munich = 48.137154, 11.576124

🥇 for starting the list at all. thanks a lot.

**Comment by iceweasel1** [comment]
I thank you! Latitude and longitude have changed. That was unintentional. I deleted the file itself and uploaded the right one. Before, it was only here for testing. For me, this is the first time with GitHub itself. Otherwise I'm here just to comment / give feedback ;-)

I added the column Sources to the list. I don't know what it's like now when someone uses the data for a visualization using csv. Should I remove the column and offer it as a separate file? (e.g. column: case number, source)

Thanks for your feedback!

**Comment by designerfuzzi** [comment]
csv is fine, as i use a iOS csv parser that can adopt any csv-column-layout. 
The more details one csv-line has, the more sorting options are possible.
Will adopt your csv-file, where ever you commit it.
The iOS app i just wrote parses the csv and triggers a mapview, quite simple yet.
I can implement a feature that helps editing new list entrys and could export to where ever you want.
As this is actually a different project then, i will open up a repositiory in myspace. kidding! in my github space!

**Comment by designerfuzzi** [comment]
if you have a friend helping you to compile, here is the yet very simple iOS app parsing your csv file, creating a list that can be touched to show map with a radius of about 20km. 
Runs on iPhone and iPads
https://github.com/designerfuzzi/Covid19
