### ISSUE TITLE
New Case North-Rhine Westfalia

### ISSUE THREAD

**Issue by eopo** [iceweasel1/COVID-19-Germany#3]
Him
another Case for Germany, a Women in the City of Essen was tested positive.

Source (unfortunately: Paywall): https://www.waz.de/staedte/essen/coronavirus-mindestens-35-neue-verdachtsfaelle-in-essen-id228586957.html

**Comment by iceweasel1** [comment]
Thank you. Plus the two police officers. That's 3 in all. I'll update the list in half an hour.

**Comment by iceweasel1** [comment]
Recent cases are now included in the list.

**Comment by dawenx** [comment]
thank you, i have updated data in our dashboard as well. :)

**Comment by eopo** [comment]
@iceweasel1 Did you include the firemen from cologne as well?

BTW first public „official“ source for the case in Essen is the major’s private Facebook page ... https://www.facebook.com/103099570021408/posts/1135149193483102/?d=n

**Comment by iceweasel1** [comment]
@eopo North Rhine-Westphalia is a very big problem with information policy. Since yesterday, no more figures are published on the website of the Ministry of Health. The reports on the website of the NRW ministry, which are updated once or twice a day, only state that the numbers in NRW have risen sharply again. As of today, for reasons unknown to me, they are starting not to make any more figures available to the population. A research to this effect is no longer really feasible for this federal state. If there are counties reporting confirmed cases from this state, I still can't assign them, because I don't know the number on/for the day X, or if it hasn't been added yet. 

Today there was no update from me for NRW. I hope that the red tape will change quickly for the better.

I don't even want to talk about the RKI. I could puke.

Almost all other affected federal states are doing very well. Either on the website, or in advance as a press release via e-mail. I'm on most of the mailing lists. But otherwise it is still the search for a needle in a haystack.

**Comment by eopo** [comment]
And another one for essen. 
Meanwhile the city of essen has seen that quick information is better, after the first and second case caused some really bad rumors.

https://www.essen.de/gesundheit/coronavirus_aktuell.de.html

**Comment by eopo** [comment]
And one of the cases in Essen was now pronounced dead: https://www.essen.de/gesundheit/coronavirus_aktuell.de.html
